/* Automatically generated by './build/bin/build-entry.js' */

import Checkbox from '../packages/checkbox/index.js';
import CheckboxButton from '../packages/checkbox-button/index.js';
import CheckboxGroup from '../packages/checkbox-group/index.js';
import Tree from '../packages/tree/index.js';

const components = [
  Checkbox,
  CheckboxButton,
  CheckboxGroup,
  Tree
];

const install = function(Vue, opts = {}) {

  components.forEach(component => {
    Vue.component(component.name, component);
  });

};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '0.1.2',
  install,
  Checkbox,
  CheckboxButton,
  CheckboxGroup,
  Tree
};
